apiVersion: v1
kind: Pod
metadata:
  name: task3-pod-sec-env
spec:
  containers:
  - name: sec-env
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    env:
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
  restartPolicy: Never