apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: task-25-nwp
  namespace: task-25-ns
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          task: task25ns
    ports:
    - protocol: TCP
      port: 80