apiVersion: v1
kind: Pod
metadata:
  name: task21-cache-pod
spec:
  containers:
  - image: nginx:latest
    name: test-container
    volumeMounts:
    - mountPath: /tmp/cache-volume
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}