kind: PersistentVolume
apiVersion: v1
metadata:
  name: mypv01
spec:
  storageClassName: slow-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/task4temp"